# Generated by Django 5.2.5 on 2025-08-29 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Telegrame', max_length=60)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('urgent_text', models.CharField(blank=True, default='', max_length=160)),
                ('urgent_link', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Setari site',
                'verbose_name_plural': 'Setari site',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField()),
                ('edition', models.CharField(choices=[('loco', 'LOCO'), ('externe', 'EXTERNE')], default='loco', max_length=8)),
                ('icon', models.CharField(default='ri-article-line', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categorii',
                'ordering': ['order', 'name'],
                'unique_together': {('slug', 'edition')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(help_text='Stire scurta / telegrama (~500 caractere)', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Publicat')], default='draft', max_length=10)),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='core.category')),
            ],
            options={
                'verbose_name': 'Articol',
                'verbose_name_plural': 'Articole',
                'ordering': ['-publish_at'],
            },
        ),
    ]
