# Generated by Django 5.2.5 on 2025-09-22 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_top',
            field=models.BooleanField(default=False, help_text="Apare dupa ':' in lista de pe pagina zilei."),
        ),
        migrations.CreateModel(
            name='HomeWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurb', models.TextField(blank=True, default='', help_text='Text scurt pentru widget (sub titlu).')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='widget', to='core.category')),
            ],
            options={
                'verbose_name': 'Widget Home',
                'verbose_name_plural': 'Widgeturi Home',
            },
        ),
    ]
